# tomcat
server:
  port: 8002
spring:
  boot:
    admin:
      client:
        url: "http://localhost:8000"
  application:
    name: mango-back
# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: 123456
      database: mango

#
management:
  endpoints:
    web:
      exposure:
        include: "*"