#消费者1
server:
  port: 8083
spring:
  application:
    name: maogo-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health

# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#熔断器
feign:
  hystrix:
    enabled: true